name: CI
on:
  - pull_request
  - push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install
        run: npm ci || npm install
      - name: XO
        run: npx xo
  Sort:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Sort reserved-names.json
        run: jq sort reserved-names.json > sort && mv sort reserved-names.json
      - name: Commit sorted file if necessary
        if: github.event_name == 'push' && github.ref != 'refs/heads/main' # Exclude PRs, no push access
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Sort reserved-names.json
      - name: Validate sorting
        if: github.event_name == 'pull_request' # Only on external PRs
        run: git diff --exit-code
        
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install
        run: npm ci || npm install
      - name: build
        run: npm run build --if-present
      - name: AVA
        run: npx ava
