# Collaborators can publish a new version of what's on master via "workflow_dispatch"
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

name: Publish

on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Version accepted by `npm version *`'
        required: true

jobs:
  NPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - run: npm install
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version ${{ github.event.inputs.Version }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags
      - uses: notlmn/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '^Meta|^\d\.\d\.\d$|^Readme|readme$|Lint|dependencies'
